### ISSUE TITLE
Acquisitions stops when running in background 

### ISSUE THREAD

**Issue by Dulco** [hidglobal/digitalpersona-devices#45]
Hey there!

Im sorry to bother to much, im doing a proyect right now.
My issue here is that everytime I minimize the browser, or click outside the page the acquisition pauses and wont get data from the fingerprint reader. It will work as usual if I click again in the page. 

I was trying to find a way to solve this issue and reading the documentation I found the library uses websockets. So i would be happy if you can help me to understand better or if there is any workaround to my problem. my main goal is to keep the fingerprint capturing fingerprints in the background.

Thanks..

**Comment by a-bronx** [comment]
Hello,

This is by design: fingerprints are collected only on the active application window. There may be several applications/pages subscribed to the fingerprint reader, but only the foreground app/page can actively collect fingerprint samples. Background web pages collecting fingerprints without user's awareness would pose a security risk. Only some native Window applications, like DigitalPersona Agent, installed into the system with user's consent, are privileged to collect fingerprints in a background, in with a lowest priority, and only for limited tasks like Windows Fast User Switch, Quick Actions etc.
